# -*- coding: utf-8 -*-
"""Tests for FRPC config rendering."""

import asyncio
import tempfile
from pathlib import Path
from unittest.mock import patch

from app.services.frpc_runtime import (
    render_frpc_config,
    write_frpc_config,
    compute_config_hash,
)


def test_render_basic() -> None:
    content = render_frpc_config(
        server_addr="127.0.0.1",
        server_port=7000,
        token="test-token",
        tunnels=[],
    )
    assert "# Auto-generated by ashan-frp" in content
    assert "server_addr = 127.0.0.1" in content
    assert "server_port = 7000" in content
    assert "token = test-token" in content
    assert "[common]" in content


def test_render_with_tunnel() -> None:
    content = render_frpc_config(
        server_addr="frp.example.com",
        server_port=7000,
        token="secret",
        tunnels=[
            {"name": "web", "type": "tcp", "local_port": 80, "remote_port": 8080},
            {"name": "ssh", "type": "tcp", "local_port": 22, "remote_port": 2222, "custom_domain": "ssh.example.com"},
        ],
    )
    assert "frp.example.com" in content
    assert "web" in content
    assert "ssh" in content
    assert "ssh.example.com" in content
    assert "[[proxies]]" in content


def test_render_escapes_token() -> None:
    content = render_frpc_config(
        server_addr="127.0.0.1",
        server_port=7000,
        token="s'ec\"ret",
        tunnels=[],
    )
    # shlex.quote will produce a TOML-safe quoted string
    # The actual output contains ec"ret which is the key part of the token
    assert "ec\"ret" in content


def test_render_with_log_level() -> None:
    content = render_frpc_config(
        server_addr="127.0.0.1",
        server_port=7000,
        token="token",
        tunnels=[],
        log_level="debug",
        log_file="/var/log/frpc.log",
    )
    assert "log_level = debug" in content
    assert "log_file = /var/log/frpc.log" in content


def test_compute_config_hash() -> None:
    h1 = compute_config_hash("abc")
    h2 = compute_config_hash("abc")
    h3 = compute_config_hash("abcd")
    assert h1 == h2
    assert h1 != h3
    assert len(h1) == 64  # sha256 hex length


def test_write_frpc_config() -> None:
    with tempfile.TemporaryDirectory() as td:
        test_dir = Path(td) / "frpc"
        test_dir.mkdir()
        with patch("app.services.frpc_runtime._work_dir", return_value=test_dir):
            config_path = asyncio.run(write_frpc_config("test content"))
            assert config_path.exists()
            assert config_path.read_text() == "test content"
