# -*- coding: utf-8 -*-
"""FRPC Runtime Manager — manages frpc process lifecycle, config rendering, health."""

from __future__ import annotations

import asyncio
import hashlib
import json
import os
import shlex
import shutil
import tempfile
import uuid
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path
from typing import Any

from app.core.config import settings
from app.db.session import SessionLocal

# Runtime states


class FrpcStatus(str, Enum):
    """FRPC process runtime status."""

    STOPPED = "stopped"
    STARTING = "starting"
    RUNNING = "running"
    DEGRADED = "degraded"
    RESTARTING = "restarting"
    FAILED = "failed"


# Singleton runtime state


class _RuntimeState:
    def __init__(self) -> None:
        self.status: FrpcStatus = FrpcStatus.STOPPED
        self.pid: int | None = None
        self.proc: asyncio.subprocess.Process | None = None  # noqa: UP045
        self.node_id: str | None = None
        self.config_hash: str | None = None
        self.started_at: datetime | None = None
        self.stopped_at: datetime | None = None
        self.last_check_at: datetime | None = None
        self.last_error: str | None = None
        self.last_heartbeat_at: datetime | None = None
        self.recovery_attempts: int = 0
        self.recovery_blocked: bool = False
        self._lock = asyncio.Lock()

    async def acquire(self) -> asyncio.Lock:
        return self._lock


_runtime = _RuntimeState()

# Paths


def _work_dir() -> Path:
    return Path(settings.FRPC_WORK_DIR)


def _config_path() -> Path:
    return _work_dir() / "frpc.toml"


def _bin_path() -> Path:
    return Path(settings.FRPC_BINARY_PATH)


def _ensure_dirs() -> None:
    _work_dir().mkdir(parents=True, exist_ok=True)
    logs_dir = _work_dir() / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)


# Config rendering


def render_frpc_config(
    server_addr: str,
    server_port: int,
    token: str,
    tunnels: list[dict[str, Any]],
    *,
    server_name: str | None = None,
    log_level: str = "info",
    log_file: str | None = None,
    admin_addr: str | None = None,
    admin_port: int | None = None,
) -> str:
    """Render frpc.toml content.

    Args:
        server_addr: FRP server address.
        server_port: FRP server port.
        token: Authentication token.
        tunnels: List of tunnel definitions.
        server_name: Optional server name.
        log_level: Log level.
        log_file: Optional log file path.
        admin_addr: Optional admin bind address.
        admin_port: Optional admin bind port.
    Returns:
        Rendered TOML string.
    """
    lines: list[str] = [
        "# Auto-generated by ashan-frp",
        f"# Generated at: {datetime.utcnow().isoformat()}Z",
    ]
    if server_name:
        lines.append(f"# Server: {server_name}")
    lines.append("")
    lines.append("[common]")
    lines.append(f'server_addr = {shlex.quote(server_addr)}')
    lines.append(f"server_port = {server_port}")
    lines.append(f'token = {shlex.quote(token)}')
    if log_level:
        lines.append(f"log_level = {shlex.quote(log_level)}")
    if log_file:
        lines.append(f"log_file = {shlex.quote(log_file)}")
    if admin_addr and admin_port:
        lines.append(f"admin_addr = {shlex.quote(admin_addr)}")
        lines.append(f"admin_port = {admin_port}")
    lines.append("")

    for tunnel in tunnels:
        name = tunnel.get("name", "default")
        lines.append(f"[[proxies]]")
        lines.append(f"name = {shlex.quote(name)}")
        lines.append(f'type = {shlex.quote(tunnel.get("type", "tcp"))}')
        local_ip = tunnel.get("local_ip", "127.0.0.1")
        local_port = tunnel.get("local_port")
        lines.append(f"local_ip = {shlex.quote(local_ip)}")
        if local_port is not None:
            lines.append(f"local_port = {local_port}")
        remote_port = tunnel.get("remote_port")
        if remote_port is not None:
            lines.append(f"remote_port = {remote_port}")
        custom_domain = tunnel.get("custom_domain")
        if custom_domain:
            lines.append(f"custom_domain = {shlex.quote(custom_domain)}")
        subdomain = tunnel.get("subdomain")
        if subdomain:
            lines.append(f"subdomain = {shlex.quote(subdomain)}")
        lines.append("")

    return "\n".join(lines)


def compute_config_hash(content: str) -> str:
    """Compute SHA-256 hash of config content."""
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


async def write_frpc_config(content: str) -> Path:
    """Write frpc.toml atomically.

    Writes to a temp file then renames to avoid readers seeing partial writes.
    """
    _ensure_dirs()
    config_file = _config_path()
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=config_file.parent,
        delete=False,
    ) as f:
        f.write(content)
        temp_path = Path(f.name)
    temp_path.replace(config_file)
    return config_file


# Process management


async def _start_frpc_process(binary: Path, config: Path) -> asyncio.subprocess.Process:
    """Spawn frpc child process with the given config."""
    cmd = [str(binary), "-c", str(config)]
    return await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )


async def _kill_proc(proc: asyncio.subprocess.Process, timeout: float = 5.0) -> None:
    """Kill a process gracefully, then forcefully if needed."""
    if proc.returncode is not None:
        return
    proc.terminate()
    try:
        await asyncio.wait_for(proc.wait(), timeout=timeout)
    except TimeoutError:
        proc.kill()
        try:
            await asyncio.wait_for(proc.wait(), timeout=2.0)
        except TimeoutError:
            pass


# Job event / audit helpers


def _add_job_event(job_id: str, event_type: str, message: str | None = None, payload: dict[str, Any] | None = None) -> None:
    """Write a job event to the database.

    Uses a new session to avoid side effects in caller sessions.
    """
    from app.models import JobEvent

    db = SessionLocal()
    try:
        count = db.query(JobEvent).filter(JobEvent.job_id == job_id).count()
        event = JobEvent(
            id=str(uuid.uuid4()),
            job_id=job_id,
            sequence_no=count + 1,
            event_type=event_type,
            level="info",
            message=message,
            payload_json=json.dumps(payload, ensure_ascii=False) if payload else None,
        )
        db.add(event)
        db.commit()
    finally:
        db.close()


def _add_audit_log(action: str, subject_type: str, subject_id: str | None, *, before_json: str | None = None, after_json: str | None = None) -> None:
    """Write an audit log entry."""
    from app.models import AuditLog

    db = SessionLocal()
    try:
        entry = AuditLog(
            id=str(uuid.uuid4()),
            account_id="system",
            actor_type="system",
            actor_id="frpc_runtime",
            action=action,
            subject_type=subject_type,
            subject_id=subject_id,
            before_json=before_json,
            after_json=after_json,
            created_at=datetime.utcnow(),
        )
        db.add(entry)
        db.commit()
    finally:
        db.close()


# Runtime manager public API


class FRPCRuntimeManager:
    """Manages frpc child process lifecycle."""

    _status_override: str | None = None

    @classmethod
    def get_status(cls) -> dict[str, Any]:
        return {
            "status": _runtime.status.value,
            "pid": _runtime.pid,
            "node_id": _runtime.node_id,
            "config_hash": _runtime.config_hash,
            "started_at": _runtime.started_at.isoformat() if _runtime.started_at else None,
            "stopped_at": _runtime.stopped_at.isoformat() if _runtime.stopped_at else None,
            "last_check_at": _runtime.last_check_at.isoformat() if _runtime.last_check_at else None,
            "last_heartbeat_at": _runtime.last_heartbeat_at.isoformat() if _runtime.last_heartbeat_at else None,
            "last_error": _runtime.last_error,
            "recovery_attempts": _runtime.recovery_attempts,
            "recovery_blocked": _runtime.recovery_blocked,
        }

    @classmethod
    async def start(cls, *, job_id: str | None = None, node_id: str | None = None) -> None:
        """Start frpc process with current config."""
        async with _runtime._lock:  # noqa: SLF001
            if _runtime.status in (FrpcStatus.RUNNING, FrpcStatus.STARTING):
                raise RuntimeError(f"frpc already in state {_runtime.status.value}")

            binary = _bin_path()
            config = _config_path()
            if not binary.exists():
                raise RuntimeError(f"frpc binary not found: {binary}")
            if not config.exists():
                raise RuntimeError(f"frpc config not found: {config}")

            _runtime.status = FrpcStatus.STARTING
            _runtime.stopped_at = None
            _runtime.last_error = None

            try:
                proc = await _start_frpc_process(binary, config)
            except Exception as exc:  # noqa: BLE001
                _runtime.status = FrpcStatus.FAILED
                _runtime.last_error = str(exc)
                msg = f"Failed to start frpc: {exc}"
                if job_id:
                    _add_job_event(job_id, "frpc.start.failed", msg)
                raise RuntimeError(msg) from exc

            _runtime.proc = proc
            _runtime.pid = proc.pid
            _runtime.started_at = datetime.utcnow()
            _runtime.node_id = node_id
            _runtime.status = FrpcStatus.RUNNING

            # Log success
            msg = f"frpc started (pid={proc.pid})"
            if job_id:
                _add_job_event(job_id, "frpc.started", msg)
            _add_audit_log(
                "frpc.start",
                "frpc_runtime",
                str(node_id) if node_id else None,
                after_json=json.dumps({"pid": proc.pid, "config_path": str(config)}),
            )

            # Fire-and-forget monitoring
            asyncio.create_task(cls._monitor_proc(proc))  # noqa: RUF006

    @classmethod
    async def stop(cls, *, job_id: str | None = None) -> None:
        """Stop the frpc process gracefully."""
        async with _runtime._lock:  # noqa: SLF001
            proc = _runtime.proc
            if proc is None or _runtime.status == FrpcStatus.STOPPED:
                return

            _runtime.status = FrpcStatus.RESTARTING if _runtime.status == FrpcStatus.RUNNING else _runtime.status
            await _kill_proc(proc)
            _runtime.status = FrpcStatus.STOPPED
            _runtime.stopped_at = datetime.utcnow()
            _runtime.pid = None
            _runtime.proc = None

            msg = "frpc stopped"
            if job_id:
                _add_job_event(job_id, "frpc.stopped", msg)
            _add_audit_log(
                "frpc.stop",
                "frpc_runtime",
                str(_runtime.node_id) if _runtime.node_id else None,
                before_json=json.dumps({"status": "running"}),
                after_json=json.dumps({"status": "stopped"}),
            )

    @classmethod
    async def restart(cls, *, job_id: str | None = None, node_id: str | None = None) -> None:
        """Restart frpc process."""
        async with _runtime._lock:  # noqa: SLF001
            was_running = _runtime.status in (FrpcStatus.RUNNING, FrpcStatus.DEGRADED)
            _runtime.status = FrpcStatus.RESTARTING

        if was_running:
            await cls.stop(job_id=job_id)

        await cls.start(job_id=job_id, node_id=node_id)

        if job_id:
            _add_job_event(job_id, "frpc.restarted", "frpc restarted successfully")

    @classmethod
    async def reload(cls, *, job_id: str | None = None) -> None:
        """Reload frpc config (restart since frpc doesn't support SIGHUP reload)."""
        async with _runtime._lock:  # noqa: SLF001
            was_running = _runtime.status in (FrpcStatus.RUNNING, FrpcStatus.DEGRADED)

        if was_running:
            await cls.restart(job_id=job_id)
        else:
            await cls.start(job_id=job_id)

        if job_id:
            _add_job_event(job_id, "frpc.reloaded", "frpc config reloaded")

    @classmethod
    async def _monitor_proc(cls, proc: asyncio.subprocess.Process) -> None:
        """Monitor frpc process and update status on exit."""
        try:
            returncode = await proc.wait()
        except Exception:  # noqa: BLE001
            return

        async with _runtime._lock:  # noqa: SLF001
            _runtime.stopped_at = datetime.utcnow()
            _runtime.pid = None
            _runtime.proc = None

            if returncode is not None and returncode != 0:
                _runtime.status = FrpcStatus.FAILED
                _runtime.last_error = f"frpc exited with code {returncode}"
            else:
                _runtime.status = FrpcStatus.STOPPED
                _runtime.last_error = None

    @classmethod
    async def health_check(cls) -> dict[str, Any]:
        """Check frpc health across process, logs, config, heartbeat, and node state."""
        now = datetime.utcnow()
        async with _runtime._lock:  # noqa: SLF001
            _runtime.last_check_at = now

            signals: dict[str, bool] = {
                "process_alive": False,
                "log_errors": False,
                "config_hash_consistent": True,
                "heartbeat_fresh": False,
                "node_online": True,
            }
            healthy = True

            proc = _runtime.proc
            if proc is None:
                healthy = False
                if _runtime.status in (
                    FrpcStatus.RUNNING,
                    FrpcStatus.DEGRADED,
                    FrpcStatus.STARTING,
                    FrpcStatus.RESTARTING,
                ):
                    _runtime.status = FrpcStatus.FAILED
                    _runtime.last_error = "Process missing but expected running"
            else:
                if proc.returncode is None:
                    signals["process_alive"] = True
                else:
                    healthy = False
                    _runtime.status = FrpcStatus.FAILED
                    _runtime.last_error = f"frpc exited with code {proc.returncode}"

            signals["log_errors"] = await cls._scan_recent_log_errors()
            if signals["log_errors"]:
                healthy = False
                if _runtime.status == FrpcStatus.RUNNING:
                    _runtime.status = FrpcStatus.DEGRADED

            signals["config_hash_consistent"] = await cls._check_config_hash_consistency()
            if not signals["config_hash_consistent"]:
                healthy = False
                if _runtime.status == FrpcStatus.RUNNING:
                    _runtime.status = FrpcStatus.DEGRADED

            if _runtime.last_heartbeat_at is not None:
                heartbeat_age = (now - _runtime.last_heartbeat_at).total_seconds()
                signals["heartbeat_fresh"] = heartbeat_age <= 90
                if not signals["heartbeat_fresh"]:
                    healthy = False
                    if _runtime.status == FrpcStatus.RUNNING:
                        _runtime.status = FrpcStatus.DEGRADED

            signals["node_online"] = await cls._check_current_node_online()
            if not signals["node_online"]:
                healthy = False
                if _runtime.status == FrpcStatus.RUNNING:
                    _runtime.status = FrpcStatus.DEGRADED

            if _runtime.status == FrpcStatus.FAILED:
                healthy = False
            if _runtime.recovery_blocked:
                healthy = False

            return {
                "healthy": healthy,
                "status": _runtime.status.value,
                "signals": signals,
                "last_check_at": now.isoformat() + "Z",
                "last_error": _runtime.last_error,
                "recovery_attempts": _runtime.recovery_attempts,
                "recovery_blocked": _runtime.recovery_blocked,
            }

    @classmethod
    async def switch_node(cls, node_id: str, *, job_id: str | None = None) -> dict[str, Any]:
        """Switch frpc to a different node.

        Validates the node exists and is active, stops the current process,
        updates runtime node_id, then restarts with the new target.
        """
        from app.models import Node

        db = SessionLocal()
        try:
            node = db.query(Node).filter(Node.id == node_id).first()
            if not node:
                raise RuntimeError(f"Node not found: {node_id}")
            if node.status != "active":
                raise RuntimeError(f"Node {node_id} is not active (status={node.status})")
        finally:
            db.close()

        was_running = _runtime.status in (FrpcStatus.RUNNING, FrpcStatus.DEGRADED, FrpcStatus.STARTING)
        if was_running:
            await cls.stop(job_id=job_id)
            async with _runtime._lock:  # noqa: SLF001
                _runtime.status = FrpcStatus.STOPPED
                _runtime.pid = None
                _runtime.proc = None

        _runtime.node_id = node_id
        _runtime.recovery_attempts = 0
        _runtime.recovery_blocked = False

        try:
            await cls.start(job_id=job_id, node_id=node_id)
        except Exception as exc:  # noqa: BLE001
            _runtime.recovery_attempts += 1
            msg = f"switch_node failed: node={node_id}, attempt={_runtime.recovery_attempts}"
            if job_id:
                _add_job_event(job_id, "frpc.switch_node.failed", msg, payload={"node_id": node_id})
            raise RuntimeError(msg) from exc

        if job_id:
            _add_job_event(job_id, "frpc.switch_node", f"frpc switched to node {node_id}", payload={"node_id": node_id})
        _add_audit_log(
            "frpc.switch_node",
            "frpc_runtime",
            node_id,
            after_json=json.dumps({"node_id": node_id, "status": "running"}),
        )
        return {"status": "switched", "node_id": node_id}

    @classmethod
    async def recover(cls, *, job_id: str | None = None, max_recovery_attempts: int = 3) -> dict[str, Any]:
        """Attempt automatic recovery of a failed or degraded frpc instance."""
        result = await cls.health_check()
        if result["healthy"]:
            _runtime.recovery_attempts = 0
            _runtime.recovery_blocked = False
            if job_id:
                _add_job_event(job_id, "frpc.recover.skipped", "Already healthy, no recovery needed")
            return {"status": "healthy", "action": "none", "details": result}

        if _runtime.recovery_blocked or _runtime.recovery_attempts >= max_recovery_attempts:
            _runtime.recovery_blocked = True
            raise RuntimeError("Recovery blocked")

        _runtime.recovery_attempts += 1
        current_node = _runtime.node_id

        if current_node:
            try:
                await cls.restart(job_id=job_id, node_id=current_node)
                check = await cls.health_check()
                if check["healthy"]:
                    _runtime.recovery_attempts = 0
                    _runtime.recovery_blocked = False
                    if job_id:
                        _add_job_event(job_id, "frpc.recovered.restart", "Recovered via restart")
                    return {"status": "recovered", "action": "restart", "node_id": current_node, "details": check}
            except Exception:  # noqa: BLE001
                pass

        try:
            from app.models import Node

            db = SessionLocal()
            try:
                alt = (
                    db.query(Node)
                    .filter(Node.status == "active", Node.id != (current_node or ""))
                    .first()
                )
            finally:
                db.close()

            if alt:
                if job_id:
                    _add_job_event(
                        job_id,
                        "frpc.recover.switching",
                        f"Attempting switch to alt node {alt.id}",
                        payload={"alt_node": alt.id},
                    )
                return await cls.switch_node(alt.id, job_id=job_id)
        except Exception:  # noqa: BLE001
            pass

        if _runtime.recovery_attempts >= max_recovery_attempts:
            _runtime.recovery_blocked = True
            if job_id:
                _add_job_event(job_id, "frpc.recover.blocked", "Recovery blocked after repeated failures")
            raise RuntimeError("Recovery blocked")

        msg = f"All recovery actions exhausted (attempt {_runtime.recovery_attempts}/{max_recovery_attempts})"
        if job_id:
            _add_job_event(job_id, "frpc.recover.exhausted", msg)
        raise RuntimeError(msg)

    @classmethod
    async def _scan_recent_log_errors(cls) -> bool:
        """Return True when recent stderr log lines show error keywords."""
        logs_dir = _work_dir() / "logs"
        stderr_path = logs_dir / "stderr.log"
        if not stderr_path.exists():
            return False

        try:
            stderr_content = stderr_path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            return False

        recent_lines = stderr_content.splitlines()[-20:]
        return any(any(keyword in line.upper() for keyword in ("ERROR", "FATAL", "PANIC")) for line in recent_lines)

    @classmethod
    async def _check_config_hash_consistency(cls) -> bool:
        """Return True when on-disk config matches the tracked hash, or when stopped with no config."""
        config_file = _config_path()
        if not config_file.exists():
            return _runtime.status == FrpcStatus.STOPPED and _runtime.config_hash is None

        if not _runtime.config_hash:
            return False

        try:
            current_content = config_file.read_text(encoding="utf-8")
        except OSError:
            return False

        return compute_config_hash(current_content) == _runtime.config_hash

    @classmethod
    async def _check_current_node_online(cls) -> bool:
        """Return True when the current node exists and is active, or when no node is bound."""
        node_id = _runtime.node_id
        if not node_id:
            return True

        from app.models import Node

        db = SessionLocal()
        try:
            node = db.query(Node).filter(Node.id == node_id).first()
            if not node:
                return False
            return node.status == "active"
        except Exception:  # noqa: BLE001
            return False
        finally:
            db.close()


# Convenience helpers for job runner


async def handle_frpc_start(db: Any, job: Any) -> dict[str, Any]:  # noqa: ARG001
    """Job handler: start frpc."""
    payload = json.loads(job.payload_json) if job.payload_json else {}
    node_id = payload.get("node_id")
    await FRPCRuntimeManager.start(job_id=job.id, node_id=node_id)
    return {"status": "started"}


async def handle_frpc_stop(db: Any, job: Any) -> dict[str, Any]:  # noqa: ARG001
    """Job handler: stop frpc."""
    await FRPCRuntimeManager.stop(job_id=job.id)
    return {"status": "stopped"}


async def handle_frpc_restart(db: Any, job: Any) -> dict[str, Any]:  # noqa: ARG001
    """Job handler: restart frpc."""
    payload = json.loads(job.payload_json) if job.payload_json else {}
    node_id = payload.get("node_id")
    await FRPCRuntimeManager.restart(job_id=job.id, node_id=node_id)
    return {"status": "restarted"}


async def handle_frpc_reload(db: Any, job: Any) -> dict[str, Any]:  # noqa: ARG001
    """Job handler: reload frpc config."""
    await FRPCRuntimeManager.reload(job_id=job.id)
    return {"status": "reloaded"}


async def handle_frpc_render_config(db: Any, job: Any) -> dict[str, Any]:  # noqa: ARG001
    """Job handler: render and write frpc.toml."""
    payload = json.loads(job.payload_json) if job.payload_json else {}
    server_addr = payload.get("server_addr", "127.0.0.1")
    server_port = payload.get("server_port", 7000)
    token = payload.get("token", "")
    tunnels = payload.get("tunnels", [])
    log_level = payload.get("log_level", "info")

    content = render_frpc_config(
        server_addr=server_addr,
        server_port=server_port,
        token=token,
        tunnels=tunnels,
        log_level=log_level,
    )
    config_file = await write_frpc_config(content)
    config_hash = compute_config_hash(content)

    return {
        "config_path": str(config_file),
        "config_hash": config_hash,
        "status": "rendered",
    }


async def handle_frpc_switch_node(db: Any, job: Any) -> dict[str, Any]:  # noqa: ARG001
    """Job handler: switch frpc to a different node."""
    payload = json.loads(job.payload_json) if job.payload_json else {}
    node_id = payload.get("node_id")
    if not node_id:
        raise RuntimeError("switch_node requires node_id in payload")
    return await FRPCRuntimeManager.switch_node(node_id, job_id=job.id)


async def handle_frpc_recover(db: Any, job: Any) -> dict[str, Any]:  # noqa: ARG001
    """Job handler: attempt automatic frpc recovery."""
    return await FRPCRuntimeManager.recover(job_id=job.id)
